#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2013-2014 Oliver Tappe
# Distributed under the terms of the MIT License.

# -- Compatibility Check ------------------------------------------------------

# TODO: use 'python2' in the shebang once we have that symlink on Haiku
import sys
if sys.version[0] != '2':
	sys.exit('Sorry, haikuporter currently requires python version 2')

# -- Modules ------------------------------------------------------------------

from HaikuPorter.Main import Main
from HaikuPorter.Options import parseOptions

# -- Start --------------------------------------------------------------------

Main(*parseOptions())
