[build-system]
requires = [ "setuptools>=80", "setuptools-scm[simple]>=9.2" ]
build-backend = "setuptools.build_meta"

[project]
name = "HaikuPorter"
authors = [ { name = "Haiku Inc.", email = "contact@haiku-inc.org" } ]
dynamic = [ "version" ]
description = "The tool that builds HaikuPorts recipes."
requires-python = ">=3.12"

[project.optional-dependencies]
test = [ "pytest" ]
doc = [ "sphinx" ]
buildmaster = [ "boto3", "paramiko", "pymongo" ]

[project.scripts]
haikuporter = "HaikuPorter.__main__:main"

[tool.setuptools.packages.find]
include = [ "HaikuPorter*" ]
