#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2016-2017 Haiku, Inc. All rights reserved.
# Distributed under the terms of the MIT License.
#
# Authors:
#   Alexander von Gluck IV <kallisti5@unixzen.com>
#

import os
import sys
import argparse
import json
from subprocess import call
from subprocess import check_output

my_location = os.path.dirname(os.path.realpath(__file__))

parser = argparse.ArgumentParser(description='Define a new package buildslave')
parser.add_argument('-n', '--name', help='Builer name', required=True)
parser.add_argument('-H', '--host', help='Builder ssh host', required=True)
parser.add_argument('-p', '--port', help='Builder ssh port', required=False, default="22")
parser.add_argument('-u', '--user', help='Builder ssh user', required=False, default="user")
parser.add_argument('-P', '--prefix', help='Base buildmaster directory', required=False, default=my_location + "/builders")
parser.add_argument('-f', '--force', help='Force recreation', required=False, action="store_true", default=False)
args = parser.parse_args()


if not os.path.isdir(args.prefix):
	os.mkdir(args.prefix, 0755)

if not os.path.isdir(args.prefix + "/keydir"):
	os.mkdir(args.prefix + "/keydir", 0700)

builder_json_path = args.prefix + "/" + args.name + ".json"
private_key_path = args.prefix + "/keydir/" + args.name
host_keys_path = args.prefix + "/keydir/" + args.name + ".hostkey"

if os.path.isfile(builder_json_path):
	if not args.force:
		print("Error: Builder '" + args.name + "' already defined. Use -f to overwrite.")
		sys.exit(1)
	os.remove(builder_json_path)

if os.path.isfile(private_key_path):
	if not args.force:
		print("Error: Builder '" + args.name + "' already defined. Use -f to overwrite.")
		sys.exit(1)
	os.remove(private_key_path)
	os.remove(private_key_path + ".pub")

print("* Creating new builder '" + args.name + "' (" + args.user + "@" + args.host + ":" + args.port + ")")
print("* Writing builder configuration...")

config = {
  "name": args.name,
  "ssh": {
    "host": args.host,
      "port": args.port,
      "user": args.user,
      "privateKeyFile": private_key_path,
      "hostKeyFile": host_keys_path
    },
    "portstree": {
      "path": "/home/haikuports",
      "packagesPath": "/home/haikuports/packages",
      "packagesCachePath": "/home/haikuports/packages/.cache"
    },
    "haikuporter": {
      "path": "haikuporter",
      "args": ""
    }
  }

with open(builder_json_path, 'w') as outfile:
	json.dump(config, outfile)

print("* Generating new keys...")
call(["ssh-keygen", "-q", "-t", "rsa", "-b", "4096", "-f", private_key_path, "-P", "", "-C", args.name])

with open(os.devnull, 'w') as devnull:
	hostkeys = check_output(["ssh-keyscan", "-t", "rsa", "-p", args.port, args.host], stderr=devnull)

with open(host_keys_path, 'w') as outfile:
	outfile.write(hostkeys)

print("* Configuration complete.\n")
print("Please authorize the following key on your builder:\n")
print("--8<-------8<-------------8<----------------")
print(check_output(["ssh-keygen", "-y", "-f", private_key_path]).strip())
print("----------8<-------8<----------------8<-----")
