#!/bin/bash

if [ $# -ne 2 ]; then
	echo "usage: $0 <git-repo-uri> <path>"
	exit 1;
fi

REPOSRC="$1"
LOCALREPO="$2"

# We do it this way so that we can abstract if from just git later on
LOCALREPO_VC_DIR=$LOCALREPO/.git

if [ ! -d $LOCALREPO_VC_DIR ]; then
	git clone $REPOSRC $LOCALREPO
else
	cd $LOCALREPO
	git pull $REPOSRC
fi
