#!/bin/sh

BASE_DIR="/var/buildmaster"
WORKDIR="$BASE_DIR/haikuports"

if [ ! -d "$WORKDIR" ]
then
	echo "buildmaster instance $WORKDIR not found, need to bootstrap?"
	exit 1
fi

if [ -z "$BUILD_TARGET_ARCH" ]
then
	echo "buildmaster instance configuration invalid"
	exit 1
fi

cd "$WORKDIR"

SUCCESS_WAIT=60
ERROR_WAIT=60

export PYTHONUNBUFFERED=1
export BUILD_TARGET_ARCH="$BUILD_TARGET_ARCH"
export REPO_DIR="/var/packages/repository/master/$BUILD_TARGET_ARCH/current"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
export SYSTEM_PACKAGES_DIR="$BASE_DIR/system-packages/$SYSTEM_PACKAGE_BRANCH"

exec 2>&1

build_prep () {
	CONSISTENCY_REPORT_FILE="$REPO_DIR/repo_consistency.txt"
	echo "repo consistency report at $(git rev-parse HEAD)" \
		> "$CONSISTENCY_REPORT_FILE"
	haikuporter --debug --check-repository-consistency \
		--no-package-obsoletion \
		--system-packages-directory $SYSTEM_PACKAGES_DIR \
		>> "$CONSISTENCY_REPORT_FILE" 2>&1

	haikuporter --debug --prune-package-repository
}

while true
do
	if [ ! -d $SYSTEM_PACKAGES_DIR ]; then
		echo "system-packages missing at $SYSTEM_PACKAGES_DIR"
		sleep $ERROR_WAIT
		continue
	fi

	echo "$(date) updating tree and pruning packages of removed ports"
	HEAD_REVISION=$(git rev-parse HEAD)
	git pull --ff-only

	if [ -f buildmaster/stop ]; then
		echo "$(date) buildmaster activity is blocked due to stop file"
		echo ""
		sleep $ERROR_WAIT
		continue
	elif [ -f buildmaster/do-everything ]; then
		echo "$(date) buildmaster everything requested, starting"
		echo ""

		rm buildmaster/do-everything

		build_prep
		buildmaster everything
	elif [ -f buildmaster/do-packages ]; then
		LIST=$(cat buildmaster/do-packages | tr '\n' ' ')
		echo "$(date) buildmaster list requested, starting the following:"
		echo "  $LIST"
		echo ""
		rm buildmaster/do-packages

		build_prep
		buildmaster build $LIST
	elif [ $(git rev-parse HEAD) = $HEAD_REVISION ]; then
		echo "$(date) no new revision"
		sleep $SUCCESS_WAIT
		continue
	else
		echo "$(date) starting buildmaster update"
		echo ""

		build_prep
		buildmaster update
	fi
	RESULT=$?

	echo ""
	if [ $RESULT -ne 0 -a $RESULT -ne 3 ]
	then
		echo "$(date) buildmaster update failed, waiting $ERROR_WAIT"
		sleep $ERROR_WAIT
		continue
	fi

	# Careful here
	REPO_SIGNING_SECRETS="/run/secrets/repo_signing"
	SIGFLAGS=""
	if [ -f $REPO_SIGNING_SECRETS/privatekey ] && [ -f $REPO_SIGNING_SECRETS/privatekeypass ]
	then
		echo "Info: Found package repository signature information."
		touch /tmp/haiku-secret.key && chmod 600 /tmp/haiku-secret.key
		echo "untrusted comment: minisign encrypted secret key" > /tmp/haiku-secret.key
		cat $REPO_SIGNING_SECRETS/privatekey >> /tmp/haiku-secret.key
		SIGFLAGS="--sign-package-repository-privkey-file /tmp/haiku-secret.key"
		SIGFLAGS="$SIGFLAGS --sign-package-repository-privkey-pass"
		SIGFLAGS="$SIGFLAGS $(cat $REPO_SIGNING_SECRETS/privatekeypass)"
	else
		echo "Info: Package repository signature information was not found."
	fi

	echo ""
	echo "$(date) pruning packages and creating repository"
	haikuporter --debug --prune-package-repository \
		--system-packages-directory $SYSTEM_PACKAGES_DIR \
		--check-package-repository-consistency \
		--create-package-repository "$REPO_DIR" \
		--storage-backend-config "$STORAGE_BACKEND_CONFIG" \
		$SIGFLAGS \
		> "$REPO_DIR/report.txt" 2>&1

	if [ $? -ne 0 ]
	then
		echo ""
		echo "$(date) create repo failed, waiting $ERROR_WAIT"
		sleep $ERROR_WAIT
		rm -f /tmp/haiku-secret.key;
		continue
	fi

	echo ""
	rm -f /tmp/haiku-secret.key;

	if [ ! -z "$REPOSITORY_TRIGGER_URL" ]
	then
		echo "$(date) requesting $REPOSITORY_TRIGGER_URL"
		curl "$REPOSITORY_TRIGGER_URL"
		echo
	fi

	echo "$(date) repo created, waiting $SUCCESS_WAIT"
	sleep $SUCCESS_WAIT
done
