default:
	docker build --no-cache --tag docker.io/haikuporter/buildmaster-frontend:1.2.7-1 .
push:
	docker push docker.io/haikuporter/buildmaster-frontend:1.2.7-1
enter:
	docker run -it docker.io/haikuporter/buildmaster-frontend:1.2.7-1 /bin/sh -l
